server:
  port: 8110 # 服务端口
spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-core # 服务名
  # 数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/srb_core?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 123456
  # redis相关配置
  redis:
    host: 192.168.56.10
    port: 6379
    database: 0
    timeout: 3000ms # 最大等待时间，超时则抛出异常
    lettuce:
      pool:
        max-active: 20 # 最大连接数，负值表示没有限制，默认为8
        max-wait: -1 # 最大阻塞时间，负值表示没有限制，默认为-1
        max-idle: 8 # 最大空闲连接数，默认为8
        min-idle: 0 # 最小空闲连接数，默认为0
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.10:8848 # 配置nacos注册中心地址
  rabbitmq:
    host: 192.168.56.10
    port: 5672
    virtual-host: /srb-host
    username: srb-user
    password: 1234
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/wwj/srb/core/mapper/xml/*.xml
