server:
  port: 8120 # 服务端口
spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-sms # 服务名
  # redis相关配置
  redis:
    host: 192.168.56.10
    port: 6379
    database: 0
    timeout: 3000ms # 最大等待时间，超时则抛出异常
    lettuce:
      pool:
        max-active: 20 # 最大连接数，负值表示没有限制，默认为8
        max-wait: -1 # 最大阻塞时间，负值表示没有限制，默认为-1
        max-idle: 8 # 最大空闲连接数，默认为8
        min-idle: 0 # 最小空闲连接数，默认为0
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.10:8848 # 配置nacos注册中心地址
  rabbitmq:
    host: 192.168.56.10
    port: 5672
    virtual-host: /srb-host
    username: srb-user
    password: 1234

# openfeign默认的超时时间为1秒，为了防止远程调用出现超时的情况，这里将超时时间设置得更长一些
feign:
  client:
    config:
      default:
        connectTimeout: 10000 # 连接超时配置
        readTimeout: 60000 # 执行超时配置
  sentinel:
    enabled: true # 开启openfeign对sentinel的支持


# 由于阿里云对个人短信验证码的审查力度过大，导致短信服务无法正常申请
# 这里使用的是尚硅谷提供的阿里云账户进行短信发送，因此短信服务随时可能会失效
# 若是失效，则采用将验证码存入redis，并直接从redis查看验证码的形式
# 阿里云短信服务配置
aliyun:
  sms:
    region-id: cn-hangzhou
    key-id: xxxx
    key-secret: xxxx
    template-code: SMS_96695065
    sign-name: 谷粒
logging:
  level:
    com.wwj.srb.sms.client.CoreUserInfoClient: DEBUG # 以debug级别监控远程服务接口